### ISSUE TITLE
Card (da página de projeto)

### ISSUE THREAD

**Issue by shogoshima** [USPCodeLabSanca/Site-USPCodeLab#12]
![image](https://github.com/USPCodeLabSanca/Site-USPCodeLab/assets/83127735/f8b9c004-b06e-4778-8438-a9203b9c3786)

**Comment by GotemBarbosa** [comment]
Card feito, mas falta a adiçao dos icones, estou no aguardo da issue #2 

Ja dei PR do card prévio (sem os ícones)

**Comment by joseCarlosAndrade** [comment]
Por favor, usem o componente `Icon` que criei no meu pr #24 para adicionar os icones

**Comment by GotemBarbosa** [comment]
@joseCarlosAndrade confirma pra mim se está tudo de acordo depois da #25, se tiver, pode fechar a issue

**Comment by joseCarlosAndrade** [comment]
PR aceita.
