### ISSUE TITLE
Colocar assets padrões (imagens, ícones)

### ISSUE THREAD

**Issue by shogoshima** [USPCodeLabSanca/Site-USPCodeLab#2]

**Comment by migueltomazini** [comment]
Ainda não adicionei todas as imagens que a gente vai utilizar. Depois a gente separa mais quais vão realmente e coloca mais pro futuro.

**Comment by GotemBarbosa** [comment]
Reabri a Issue, é melhor fechar a issue quando houver alguma biblioteca adicionada para poder pegar os icones de tecnologia que nem no figma

![image](https://github.com/USPCodeLabSanca/Site-USPCodeLab/assets/50121055/13380c06-7324-4269-8621-70545e35c295)

**Comment by GotemBarbosa** [comment]
Feito na #24

**Comment by GotemBarbosa** [comment]
Feito na #24,
