### ISSUE TITLE
Fazer alguns modelos de formatos Bezier da página principal

### ISSUE THREAD

**Issue by shogoshima** [USPCodeLabSanca/Site-USPCodeLab#34]
Links úteis:
https://blog.logrocket.com/15-best-css-shape-generators-demo/
https://app.haikei.app/

![image](https://github.com/USPCodeLabSanca/Site-USPCodeLab/assets/83127735/a48da350-13b1-471a-b482-de70b1189143)

**Comment by GotemBarbosa** [comment]
feito em #52
