### ISSUE TITLE
Responsividade completa dos cards de projeto

### ISSUE THREAD

**Issue by joseCarlosAndrade** [USPCodeLabSanca/Site-USPCodeLab#50]
A responsividade dos icones dos cards de projeto nao está 100%. E acontece quando:

Reduzimos o tamanho da largura da tela de forma que alguns cards reduzam (icones vao para a esquerda e diminuem proporcionalmente) mas outros cards com textos menores continuam da mesma forma, gerando icones de tamanho diferentes:

![image](https://github.com/USPCodeLabSanca/Site-USPCodeLab/assets/89979529/2a8a6a70-3c07-4ebc-bfc6-5098f8aa6fc0)

**Comment by joseCarlosAndrade** [comment]
Ajeitar inconsistencia das barras separadoras do navbar:
![image](https://github.com/USPCodeLabSanca/Site-USPCodeLab/assets/89979529/03a5d0ea-dad3-4dc6-ab39-4868761a1c60)

**Comment by GotemBarbosa** [comment]
Feito em #54 e #55
