### ISSUE TITLE
AJustar a responsividade da parte inicial da home section

### ISSUE THREAD

**Issue by GotemBarbosa** [USPCodeLabSanca/Site-USPCodeLab#61]
![image](https://github.com/USPCodeLabSanca/Site-USPCodeLab/assets/50121055/097a1a07-b681-43ec-8bf1-217fcb9dacb3)

**Comment by Windows87** [comment]
<img width="292" alt="Captura de Tela 2024-07-30 às 16 11 55" src="https://github.com/user-attachments/assets/11a84309-dd98-4e7f-a320-b115560d68c8">

Colocar a Logo acima ou removê-la no mobile

<img width="313" alt="Captura de Tela 2024-07-30 às 16 14 35" src="https://github.com/user-attachments/assets/5045ffe8-4137-477b-8eaa-1f39d476e0fc">

Grande distanciamento

<img width="311" alt="Captura de Tela 2024-07-30 às 16 15 05" src="https://github.com/user-attachments/assets/f5bba61b-4816-46aa-a0f4-dc7ccaeb2552">

Sem margem o texto final e muita margem o texto pequeno

<img width="329" alt="Captura de Tela 2024-07-30 às 16 23 06" src="https://github.com/user-attachments/assets/18d9a801-f86d-4c08-a7fe-8fd2a85c8c8b">

Bug animação
