### ISSUE TITLE
Componente de Scroll de imagens

### ISSUE THREAD

**Issue by shogoshima** [USPCodeLabSanca/Site-USPCodeLab#8]
Caso você pegue essa issue, ter certeza do que se quer. Caso necessário, perguntar no grupo como é para fazer.
É para ser como se fosse um scroll automático e lento de imagens de baixo para cima. 

![image](https://github.com/USPCodeLabSanca/Site-USPCodeLab/assets/83127735/e7f2f36c-4dad-416c-97af-fb4efab41002)

**Comment by joseCarlosAndrade** [comment]
Feito no pr #27 . Possíveis mudanças a serem atacadas, mas funcionamento básico concluído. Nao vou fechar a issue por enquanto para deixar aberto a novas implementaçoes.
